// =============================================================================
// Cena Adaptive Learning Platform — State Management Contracts (Riverpod)
// All providers use code-generation style with proper auto-dispose.
// =============================================================================

import 'dart:async';

import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../models/domain_models.dart';
import '../services/offline_sync_service.dart';
import '../services/websocket_service.dart';

// ==========================================================================
// Session State
// ==========================================================================

/// State for the active learning session.
class SessionState {
  const SessionState({
    this.currentSession,
    this.currentExercise,
    this.methodology,
    this.fatigueScore = 0.0,
    this.questionsAttempted = 0,
    this.questionsCorrect = 0,
    this.isLoading = false,
    this.error,
    this.isBreakSuggested = false,
    this.hintsUsed = 0,
    this.sessionHistory = const [],
  });

  final Session? currentSession;
  final Exercise? currentExercise;
  final Methodology? methodology;
  final double fatigueScore;
  final int questionsAttempted;
  final int questionsCorrect;
  final bool isLoading;
  final String? error;
  final bool isBreakSuggested;
  final int hintsUsed;

  /// Recent answer results for the progress display.
  final List<AnswerResult> sessionHistory;

  bool get isActive => currentSession != null && currentSession!.endedAt == null;
  double get accuracy =>
      questionsAttempted > 0 ? questionsCorrect / questionsAttempted : 0.0;
  Duration get elapsed => currentSession != null
      ? DateTime.now().difference(currentSession!.startedAt)
      : Duration.zero;

  SessionState copyWith({
    Session? currentSession,
    Exercise? currentExercise,
    Methodology? methodology,
    double? fatigueScore,
    int? questionsAttempted,
    int? questionsCorrect,
    bool? isLoading,
    String? error,
    bool? isBreakSuggested,
    int? hintsUsed,
    List<AnswerResult>? sessionHistory,
  }) {
    return SessionState(
      currentSession: currentSession ?? this.currentSession,
      currentExercise: currentExercise ?? this.currentExercise,
      methodology: methodology ?? this.methodology,
      fatigueScore: fatigueScore ?? this.fatigueScore,
      questionsAttempted: questionsAttempted ?? this.questionsAttempted,
      questionsCorrect: questionsCorrect ?? this.questionsCorrect,
      isLoading: isLoading ?? this.isLoading,
      error: error ?? this.error,
      isBreakSuggested: isBreakSuggested ?? this.isBreakSuggested,
      hintsUsed: hintsUsed ?? this.hintsUsed,
      sessionHistory: sessionHistory ?? this.sessionHistory,
    );
  }
}

/// Manages the active learning session lifecycle.
///
/// Listens to WebSocket events for question delivery, answer evaluation,
/// methodology switches, and cognitive load warnings.
class SessionNotifier extends StateNotifier<SessionState> {
  SessionNotifier({
    required this.webSocketService,
    required this.syncManager,
  }) : super(const SessionState()) {
    _subscribeToEvents();
  }

  final WebSocketService webSocketService;
  final SyncManager syncManager;
  final List<StreamSubscription<dynamic>> _subscriptions = [];

  /// Start a new learning session.
  Future<void> startSession({Subject? subject, int durationMinutes = 25}) async {
    state = state.copyWith(isLoading: true, error: null);
    try {
      await webSocketService.startSession(StartSession(
        studentId: '', // Injected from UserNotifier
        subject: subject,
        durationMinutes: durationMinutes,
      ));
    } catch (e) {
      state = state.copyWith(isLoading: false, error: e.toString());
    }
  }

  /// Submit an answer to the current exercise.
  Future<void> submitAnswer(String answer, int timeSpentMs) async {
    final exercise = state.currentExercise;
    if (exercise == null) return;

    await webSocketService.attemptConcept(AttemptConcept(
      sessionId: state.currentSession!.id,
      exerciseId: exercise.id,
      conceptId: exercise.conceptId,
      answer: answer,
      timeSpentMs: timeSpentMs,
      idempotencyKey: '', // Generated by implementation
    ));
  }

  /// Request a hint for the current exercise.
  Future<void> requestHint() async {
    final exercise = state.currentExercise;
    final session = state.currentSession;
    if (exercise == null || session == null) return;

    await webSocketService.requestHint(RequestHint(
      sessionId: session.id,
      exerciseId: exercise.id,
      hintLevel: state.hintsUsed,
    ));
    state = state.copyWith(hintsUsed: state.hintsUsed + 1);
  }

  /// Skip the current question.
  Future<void> skipQuestion({String? reason}) async {
    final exercise = state.currentExercise;
    final session = state.currentSession;
    if (exercise == null || session == null) return;

    await webSocketService.skipQuestion(SkipQuestion(
      sessionId: session.id,
      exerciseId: exercise.id,
      reason: reason,
    ));
  }

  /// Request a different pedagogical approach.
  Future<void> switchApproach(String preferenceHint) async {
    final session = state.currentSession;
    if (session == null) return;

    await webSocketService.switchApproach(SwitchApproach(
      sessionId: session.id,
      preferenceHint: preferenceHint,
    ));
  }

  /// End the current session.
  Future<void> endSession({String reason = 'manual'}) async {
    final session = state.currentSession;
    if (session == null) return;

    await webSocketService.endSession(EndSession(
      sessionId: session.id,
      reason: reason,
    ));
  }

  /// Acknowledge the break suggestion and continue or take a break.
  void dismissBreakSuggestion() {
    state = state.copyWith(isBreakSuggested: false);
  }

  void _subscribeToEvents() {
    // Implementation subscribes to WebSocket message stream and routes events:
    // - QuestionPresented → update currentExercise, increment attempted
    // - AnswerEvaluated → update sessionHistory, increment correct if applicable
    // - MethodologySwitched → update methodology
    // - CognitiveLoadWarning → update fatigueScore, set isBreakSuggested
    // - SessionSummary → mark session ended
  }

  @override
  void dispose() {
    for (final sub in _subscriptions) {
      sub.cancel();
    }
    super.dispose();
  }
}

// ==========================================================================
// Knowledge Graph State
// ==========================================================================

/// State for the interactive knowledge graph visualization.
class KnowledgeGraphState {
  const KnowledgeGraphState({
    this.graph,
    this.selectedNodeId,
    this.subjectFilter,
    this.zoomLevel = 1.0,
    this.panOffsetX = 0.0,
    this.panOffsetY = 0.0,
    this.isLoading = false,
    this.error,
    this.searchQuery,
    this.highlightedPath = const [],
  });

  final KnowledgeGraph? graph;
  final String? selectedNodeId;
  final Subject? subjectFilter;
  final double zoomLevel;
  final double panOffsetX;
  final double panOffsetY;
  final bool isLoading;
  final String? error;
  final String? searchQuery;

  /// Node IDs along the highlighted prerequisite path.
  final List<String> highlightedPath;

  ConceptNode? get selectedNode => graph?.nodes
      .cast<ConceptNode?>()
      .firstWhere((n) => n?.conceptId == selectedNodeId, orElse: () => null);

  List<ConceptNode> get filteredNodes {
    if (graph == null) return [];
    if (subjectFilter == null) return graph!.nodes;
    return graph!.nodes.where((n) => n.subject == subjectFilter).toList();
  }

  KnowledgeGraphState copyWith({
    KnowledgeGraph? graph,
    String? selectedNodeId,
    Subject? subjectFilter,
    double? zoomLevel,
    double? panOffsetX,
    double? panOffsetY,
    bool? isLoading,
    String? error,
    String? searchQuery,
    List<String>? highlightedPath,
  }) {
    return KnowledgeGraphState(
      graph: graph ?? this.graph,
      selectedNodeId: selectedNodeId ?? this.selectedNodeId,
      subjectFilter: subjectFilter ?? this.subjectFilter,
      zoomLevel: zoomLevel ?? this.zoomLevel,
      panOffsetX: panOffsetX ?? this.panOffsetX,
      panOffsetY: panOffsetY ?? this.panOffsetY,
      isLoading: isLoading ?? this.isLoading,
      error: error ?? this.error,
      searchQuery: searchQuery ?? this.searchQuery,
      highlightedPath: highlightedPath ?? this.highlightedPath,
    );
  }
}

/// Manages the knowledge graph visualization state.
///
/// Receives graph updates from the WebSocket service and handles
/// user interactions (select node, filter by subject, zoom, pan).
class KnowledgeGraphNotifier extends StateNotifier<KnowledgeGraphState> {
  KnowledgeGraphNotifier({
    required this.webSocketService,
  }) : super(const KnowledgeGraphState()) {
    _subscribeToEvents();
  }

  final WebSocketService webSocketService;
  StreamSubscription<MessageEnvelope>? _subscription;

  /// Select a concept node in the graph.
  void selectNode(String? conceptId) {
    state = state.copyWith(selectedNodeId: conceptId);
  }

  /// Filter the graph to show only one subject.
  void filterBySubject(Subject? subject) {
    state = state.copyWith(subjectFilter: subject);
  }

  /// Update zoom level (clamped to [0.3, 3.0]).
  void setZoom(double zoom) {
    state = state.copyWith(zoomLevel: zoom.clamp(0.3, 3.0));
  }

  /// Update pan offset.
  void setPanOffset(double x, double y) {
    state = state.copyWith(panOffsetX: x, panOffsetY: y);
  }

  /// Search concepts by name.
  void search(String? query) {
    state = state.copyWith(searchQuery: query);
  }

  /// Highlight the prerequisite path to a target concept.
  void highlightPathTo(String conceptId) {
    // Implementation: BFS/DFS from root concepts to the target,
    // collecting the path of concept IDs.
    state = state.copyWith(highlightedPath: [conceptId]);
  }

  /// Clear the highlighted path.
  void clearHighlight() {
    state = state.copyWith(highlightedPath: []);
  }

  void _subscribeToEvents() {
    // Implementation: listen to KnowledgeGraphUpdated events from WebSocket
  }

  @override
  void dispose() {
    _subscription?.cancel();
    super.dispose();
  }
}

// ==========================================================================
// User State
// ==========================================================================

/// State for the authenticated student user.
class UserState {
  const UserState({
    this.student,
    this.badges = const [],
    this.dailyQuestionsAnswered = 0,
    this.dailyGoal = 20,
    this.llmInteractionsToday = 0,
    this.isLoading = false,
    this.error,
  });

  final Student? student;
  final List<Badge> badges;
  final int dailyQuestionsAnswered;
  final int dailyGoal;

  /// Number of LLM interactions used today (cap: 50 = "study energy").
  final int llmInteractionsToday;
  final bool isLoading;
  final String? error;

  bool get isAuthenticated => student != null;
  int get remainingStudyEnergy => 50 - llmInteractionsToday;
  bool get hasStudyEnergy => llmInteractionsToday < 50;
  double get dailyProgress =>
      dailyGoal > 0 ? (dailyQuestionsAnswered / dailyGoal).clamp(0.0, 1.0) : 0.0;

  UserState copyWith({
    Student? student,
    List<Badge>? badges,
    int? dailyQuestionsAnswered,
    int? dailyGoal,
    int? llmInteractionsToday,
    bool? isLoading,
    String? error,
  }) {
    return UserState(
      student: student ?? this.student,
      badges: badges ?? this.badges,
      dailyQuestionsAnswered:
          dailyQuestionsAnswered ?? this.dailyQuestionsAnswered,
      dailyGoal: dailyGoal ?? this.dailyGoal,
      llmInteractionsToday:
          llmInteractionsToday ?? this.llmInteractionsToday,
      isLoading: isLoading ?? this.isLoading,
      error: error ?? this.error,
    );
  }
}

/// Manages authenticated user state, XP, streaks, and badges.
class UserNotifier extends StateNotifier<UserState> {
  UserNotifier({
    required this.webSocketService,
  }) : super(const UserState()) {
    _subscribeToEvents();
  }

  final WebSocketService webSocketService;
  final List<StreamSubscription<dynamic>> _subscriptions = [];

  /// Set the authenticated student (called after login).
  void setStudent(Student student) {
    state = state.copyWith(student: student);
  }

  /// Clear user state on logout.
  void logout() {
    state = const UserState();
  }

  /// Increment the daily question counter.
  void recordQuestionAttempt() {
    state = state.copyWith(
      dailyQuestionsAnswered: state.dailyQuestionsAnswered + 1,
    );
  }

  /// Increment LLM interaction counter (tracks "study energy").
  void recordLlmInteraction() {
    state = state.copyWith(
      llmInteractionsToday: state.llmInteractionsToday + 1,
    );
  }

  void _subscribeToEvents() {
    // Implementation: listen to XpAwarded, StreakUpdated, badge events
  }

  @override
  void dispose() {
    for (final sub in _subscriptions) {
      sub.cancel();
    }
    super.dispose();
  }
}

// ==========================================================================
// Offline / Sync State
// ==========================================================================

/// State for offline sync status and queue monitoring.
class OfflineState {
  const OfflineState({
    this.queuedEventCount = 0,
    this.syncStatus = SyncStatus.idle,
    this.lastSyncTime,
    this.isOnline = true,
    this.lastError,
    this.conflictCount = 0,
  });

  final int queuedEventCount;
  final SyncStatus syncStatus;
  final DateTime? lastSyncTime;
  final bool isOnline;
  final String? lastError;
  final int conflictCount;

  bool get hasPendingEvents => queuedEventCount > 0;
  bool get hasConflicts => conflictCount > 0;
  bool get isSyncing => syncStatus == SyncStatus.syncing;

  OfflineState copyWith({
    int? queuedEventCount,
    SyncStatus? syncStatus,
    DateTime? lastSyncTime,
    bool? isOnline,
    String? lastError,
    int? conflictCount,
  }) {
    return OfflineState(
      queuedEventCount: queuedEventCount ?? this.queuedEventCount,
      syncStatus: syncStatus ?? this.syncStatus,
      lastSyncTime: lastSyncTime ?? this.lastSyncTime,
      isOnline: isOnline ?? this.isOnline,
      lastError: lastError ?? this.lastError,
      conflictCount: conflictCount ?? this.conflictCount,
    );
  }
}

/// Monitors offline event queue and sync lifecycle.
class OfflineNotifier extends StateNotifier<OfflineState> {
  OfflineNotifier({
    required this.syncManager,
    required this.connectivityMonitor,
  }) : super(const OfflineState()) {
    _startMonitoring();
  }

  final SyncManager syncManager;
  final ConnectivityMonitor connectivityMonitor;
  final List<StreamSubscription<dynamic>> _subscriptions = [];

  /// Trigger an immediate sync attempt.
  Future<bool> syncNow() => syncManager.syncNow();

  void _startMonitoring() {
    _subscriptions.add(
      syncManager.statusStream.listen((status) {
        state = state.copyWith(syncStatus: status);
      }),
    );
    _subscriptions.add(
      syncManager.pendingEventCountStream.listen((count) {
        state = state.copyWith(queuedEventCount: count);
      }),
    );
    _subscriptions.add(
      syncManager.lastSyncTimeStream.listen((time) {
        state = state.copyWith(lastSyncTime: time);
      }),
    );
    _subscriptions.add(
      connectivityMonitor.onConnectivityChanged.listen((online) {
        state = state.copyWith(isOnline: online);
      }),
    );
  }

  @override
  void dispose() {
    for (final sub in _subscriptions) {
      sub.cancel();
    }
    super.dispose();
  }
}

// ==========================================================================
// Outreach / Notification State
// ==========================================================================

/// State for push notifications and streak warnings.
class OutreachState {
  const OutreachState({
    this.pendingNotifications = const [],
    this.streakExpiresAt,
    this.isStreakWarningActive = false,
    this.lastNotificationDismissedAt,
  });

  final List<AppNotification> pendingNotifications;
  final DateTime? streakExpiresAt;
  final bool isStreakWarningActive;
  final DateTime? lastNotificationDismissedAt;

  int get unreadCount => pendingNotifications.where((n) => !n.isRead).length;

  OutreachState copyWith({
    List<AppNotification>? pendingNotifications,
    DateTime? streakExpiresAt,
    bool? isStreakWarningActive,
    DateTime? lastNotificationDismissedAt,
  }) {
    return OutreachState(
      pendingNotifications: pendingNotifications ?? this.pendingNotifications,
      streakExpiresAt: streakExpiresAt ?? this.streakExpiresAt,
      isStreakWarningActive:
          isStreakWarningActive ?? this.isStreakWarningActive,
      lastNotificationDismissedAt:
          lastNotificationDismissedAt ?? this.lastNotificationDismissedAt,
    );
  }
}

/// A local notification model.
class AppNotification {
  const AppNotification({
    required this.id,
    required this.title,
    required this.body,
    required this.createdAt,
    this.isRead = false,
    this.actionRoute,
  });

  final String id;
  final String title;
  final String body;
  final DateTime createdAt;
  final bool isRead;

  /// Optional deep link route, e.g. "/session/start" or "/graph/concept/123".
  final String? actionRoute;
}

/// Manages notifications and streak warnings.
class OutreachNotifier extends StateNotifier<OutreachState> {
  OutreachNotifier() : super(const OutreachState());

  /// Add a new notification.
  void addNotification(AppNotification notification) {
    state = state.copyWith(
      pendingNotifications: [...state.pendingNotifications, notification],
    );
  }

  /// Mark a notification as read.
  void markRead(String notificationId) {
    state = state.copyWith(
      pendingNotifications: state.pendingNotifications.map((n) {
        if (n.id == notificationId) {
          return AppNotification(
            id: n.id,
            title: n.title,
            body: n.body,
            createdAt: n.createdAt,
            isRead: true,
            actionRoute: n.actionRoute,
          );
        }
        return n;
      }).toList(),
    );
  }

  /// Dismiss all notifications.
  void dismissAll() {
    state = state.copyWith(
      pendingNotifications: [],
      lastNotificationDismissedAt: DateTime.now(),
    );
  }

  /// Activate streak expiration warning.
  void warnStreakExpiring(DateTime expiresAt) {
    state = state.copyWith(
      streakExpiresAt: expiresAt,
      isStreakWarningActive: true,
    );
  }

  /// Dismiss streak warning (student acknowledged).
  void dismissStreakWarning() {
    state = state.copyWith(isStreakWarningActive: false);
  }
}

// ==========================================================================
// Provider Declarations
// ==========================================================================

/// WebSocket service provider — overridden in the provider scope at app startup.
final webSocketServiceProvider = Provider<WebSocketService>((ref) {
  throw UnimplementedError(
    'WebSocketService must be overridden in ProviderScope',
  );
});

/// Sync manager provider — overridden in the provider scope at app startup.
final syncManagerProvider = Provider<SyncManager>((ref) {
  throw UnimplementedError(
    'SyncManager must be overridden in ProviderScope',
  );
});

/// Connectivity monitor provider.
final connectivityMonitorProvider = Provider<ConnectivityMonitor>((ref) {
  throw UnimplementedError(
    'ConnectivityMonitor must be overridden in ProviderScope',
  );
});

/// Session state provider (auto-disposed when no listeners).
final sessionProvider =
    StateNotifierProvider.autoDispose<SessionNotifier, SessionState>((ref) {
  return SessionNotifier(
    webSocketService: ref.watch(webSocketServiceProvider),
    syncManager: ref.watch(syncManagerProvider),
  );
});

/// Knowledge graph state provider.
final knowledgeGraphProvider = StateNotifierProvider.autoDispose<
    KnowledgeGraphNotifier, KnowledgeGraphState>((ref) {
  return KnowledgeGraphNotifier(
    webSocketService: ref.watch(webSocketServiceProvider),
  );
});

/// User state provider (kept alive — user is always relevant).
final userProvider =
    StateNotifierProvider<UserNotifier, UserState>((ref) {
  return UserNotifier(
    webSocketService: ref.watch(webSocketServiceProvider),
  );
});

/// Offline sync state provider.
final offlineProvider =
    StateNotifierProvider<OfflineNotifier, OfflineState>((ref) {
  return OfflineNotifier(
    syncManager: ref.watch(syncManagerProvider),
    connectivityMonitor: ref.watch(connectivityMonitorProvider),
  );
});

/// Outreach / notification state provider.
final outreachProvider =
    StateNotifierProvider<OutreachNotifier, OutreachState>((ref) {
  return OutreachNotifier();
});

// ==========================================================================
// Derived / Selector Providers
// ==========================================================================

/// Whether the student is currently in an active session.
final isSessionActiveProvider = Provider.autoDispose<bool>((ref) {
  return ref.watch(sessionProvider.select((s) => s.isActive));
});

/// Current connection state from the WebSocket service.
final connectionStateProvider = StreamProvider.autoDispose<ConnectionState>((ref) {
  return ref.watch(webSocketServiceProvider).connectionState;
});

/// Whether there are pending offline events to sync.
final hasPendingEventsProvider = Provider.autoDispose<bool>((ref) {
  return ref.watch(offlineProvider.select((s) => s.hasPendingEvents));
});

/// Remaining "study energy" (LLM interaction budget).
final remainingStudyEnergyProvider = Provider.autoDispose<int>((ref) {
  return ref.watch(userProvider.select((s) => s.remainingStudyEnergy));
});

/// Subject-filtered knowledge graph for the selected filter.
final filteredGraphNodesProvider =
    Provider.autoDispose<List<ConceptNode>>((ref) {
  return ref.watch(knowledgeGraphProvider.select((s) => s.filteredNodes));
});

/// Selected concept node, if any.
final selectedConceptProvider = Provider.autoDispose<ConceptNode?>((ref) {
  return ref.watch(knowledgeGraphProvider.select((s) => s.selectedNode));
});
