/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    'dev-design-system': RouteRecordInfo<'dev-design-system', '/_dev/design-system', Record<never, never>, Record<never, never>>,
    'dev-flow-states': RouteRecordInfo<'dev-flow-states', '/_dev/flow-states', Record<never, never>, Record<never, never>>,
    'dev-probe': RouteRecordInfo<'dev-probe', '/_dev/probe', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'accessibility-statement': RouteRecordInfo<'accessibility-statement', '/accessibility-statement', Record<never, never>, Record<never, never>>,
    'challenges': RouteRecordInfo<'challenges', '/challenges', Record<never, never>, Record<never, never>>,
    'challenges-boss': RouteRecordInfo<'challenges-boss', '/challenges/boss', Record<never, never>, Record<never, never>>,
    'challenges-chains-chain-id': RouteRecordInfo<'challenges-chains-chain-id', '/challenges/chains/:chainId', { chainId: ParamValue<true> }, { chainId: ParamValue<false> }>,
    'challenges-daily': RouteRecordInfo<'challenges-daily', '/challenges/daily', Record<never, never>, Record<never, never>>,
    'diagrams-diagram-id': RouteRecordInfo<'diagrams-diagram-id', '/diagrams/:diagramId', { diagramId: ParamValue<true> }, { diagramId: ParamValue<false> }>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'home': RouteRecordInfo<'home', '/home', Record<never, never>, Record<never, never>>,
    'knowledge-graph': RouteRecordInfo<'knowledge-graph', '/knowledge-graph', Record<never, never>, Record<never, never>>,
    'knowledge-graph-concept-id': RouteRecordInfo<'knowledge-graph-concept-id', '/knowledge-graph/concept/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'notifications': RouteRecordInfo<'notifications', '/notifications', Record<never, never>, Record<never, never>>,
    'onboarding': RouteRecordInfo<'onboarding', '/onboarding', Record<never, never>, Record<never, never>>,
    'pricing': RouteRecordInfo<'pricing', '/pricing', Record<never, never>, Record<never, never>>,
    'privacy': RouteRecordInfo<'privacy', '/privacy', Record<never, never>, Record<never, never>>,
    'privacy-children': RouteRecordInfo<'privacy-children', '/privacy/children', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'profile-edit': RouteRecordInfo<'profile-edit', '/profile/edit', Record<never, never>, Record<never, never>>,
    'progress': RouteRecordInfo<'progress', '/progress', Record<never, never>, Record<never, never>>,
    'progress-mastery': RouteRecordInfo<'progress-mastery', '/progress/mastery', Record<never, never>, Record<never, never>>,
    'progress-sessions': RouteRecordInfo<'progress-sessions', '/progress/sessions', Record<never, never>, Record<never, never>>,
    'progress-sessions-session-id': RouteRecordInfo<'progress-sessions-session-id', '/progress/sessions/:sessionId', { sessionId: ParamValue<true> }, { sessionId: ParamValue<false> }>,
    'progress-time': RouteRecordInfo<'progress-time', '/progress/time', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'session': RouteRecordInfo<'session', '/session', Record<never, never>, Record<never, never>>,
    'session-session-id': RouteRecordInfo<'session-session-id', '/session/:sessionId', { sessionId: ParamValue<true> }, { sessionId: ParamValue<false> }>,
    'session-session-id-replay': RouteRecordInfo<'session-session-id-replay', '/session/:sessionId/replay', { sessionId: ParamValue<true> }, { sessionId: ParamValue<false> }>,
    'session-session-id-summary': RouteRecordInfo<'session-session-id-summary', '/session/:sessionId/summary', { sessionId: ParamValue<true> }, { sessionId: ParamValue<false> }>,
    'settings': RouteRecordInfo<'settings', '/settings', Record<never, never>, Record<never, never>>,
    'settings-account': RouteRecordInfo<'settings-account', '/settings/account', Record<never, never>, Record<never, never>>,
    'settings-appearance': RouteRecordInfo<'settings-appearance', '/settings/appearance', Record<never, never>, Record<never, never>>,
    'settings-notifications': RouteRecordInfo<'settings-notifications', '/settings/notifications', Record<never, never>, Record<never, never>>,
    'settings-privacy': RouteRecordInfo<'settings-privacy', '/settings/privacy', Record<never, never>, Record<never, never>>,
    'settings-study-plan': RouteRecordInfo<'settings-study-plan', '/settings/study-plan', Record<never, never>, Record<never, never>>,
    'social': RouteRecordInfo<'social', '/social', Record<never, never>, Record<never, never>>,
    'social-friends': RouteRecordInfo<'social-friends', '/social/friends', Record<never, never>, Record<never, never>>,
    'social-leaderboard': RouteRecordInfo<'social-leaderboard', '/social/leaderboard', Record<never, never>, Record<never, never>>,
    'social-peers': RouteRecordInfo<'social-peers', '/social/peers', Record<never, never>, Record<never, never>>,
    'terms': RouteRecordInfo<'terms', '/terms', Record<never, never>, Record<never, never>>,
    'tutor': RouteRecordInfo<'tutor', '/tutor', Record<never, never>, Record<never, never>>,
    'tutor-thread-id': RouteRecordInfo<'tutor-thread-id', '/tutor/:threadId', { threadId: ParamValue<true> }, { threadId: ParamValue<false> }>,
    'tutor-pdf-upload': RouteRecordInfo<'tutor-pdf-upload', '/tutor/pdf-upload', Record<never, never>, Record<never, never>>,
    'tutor-photo-capture': RouteRecordInfo<'tutor-photo-capture', '/tutor/photo-capture', Record<never, never>, Record<never, never>>,
  }
}
