/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'apps-cultural-dashboard': RouteRecordInfo<'apps-cultural-dashboard', '/apps/cultural/dashboard', Record<never, never>, Record<never, never>>,
    'apps-experiments': RouteRecordInfo<'apps-experiments', '/apps/experiments', Record<never, never>, Record<never, never>>,
    'apps-experiments-id': RouteRecordInfo<'apps-experiments-id', '/apps/experiments/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-focus-class-id': RouteRecordInfo<'apps-focus-class-id', '/apps/focus/class/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-focus-dashboard': RouteRecordInfo<'apps-focus-dashboard', '/apps/focus/dashboard', Record<never, never>, Record<never, never>>,
    'apps-focus-student-id': RouteRecordInfo<'apps-focus-student-id', '/apps/focus/student/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-ingestion-pipeline': RouteRecordInfo<'apps-ingestion-pipeline', '/apps/ingestion/pipeline', Record<never, never>, Record<never, never>>,
    'apps-ingestion-settings': RouteRecordInfo<'apps-ingestion-settings', '/apps/ingestion/settings', Record<never, never>, Record<never, never>>,
    'apps-mastery-class-id': RouteRecordInfo<'apps-mastery-class-id', '/apps/mastery/class/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-mastery-dashboard': RouteRecordInfo<'apps-mastery-dashboard', '/apps/mastery/dashboard', Record<never, never>, Record<never, never>>,
    'apps-mastery-student-id': RouteRecordInfo<'apps-mastery-student-id', '/apps/mastery/student/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-messaging': RouteRecordInfo<'apps-messaging', '/apps/messaging', Record<never, never>, Record<never, never>>,
    'apps-messaging-thread-id': RouteRecordInfo<'apps-messaging-thread-id', '/apps/messaging/:threadId', { threadId: ParamValue<true> }, { threadId: ParamValue<false> }>,
    'apps-moderation-queue': RouteRecordInfo<'apps-moderation-queue', '/apps/moderation/queue', Record<never, never>, Record<never, never>>,
    'apps-moderation-review-id': RouteRecordInfo<'apps-moderation-review-id', '/apps/moderation/review/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-outreach-dashboard': RouteRecordInfo<'apps-outreach-dashboard', '/apps/outreach/dashboard', Record<never, never>, Record<never, never>>,
    'apps-pedagogy-mcm-graph': RouteRecordInfo<'apps-pedagogy-mcm-graph', '/apps/pedagogy/mcm-graph', Record<never, never>, Record<never, never>>,
    'apps-pedagogy-methodology': RouteRecordInfo<'apps-pedagogy-methodology', '/apps/pedagogy/methodology', Record<never, never>, Record<never, never>>,
    'apps-pedagogy-methodology-hierarchy': RouteRecordInfo<'apps-pedagogy-methodology-hierarchy', '/apps/pedagogy/methodology-hierarchy', Record<never, never>, Record<never, never>>,
    'apps-permissions': RouteRecordInfo<'apps-permissions', '/apps/permissions', Record<never, never>, Record<never, never>>,
    'apps-questions-edit-id': RouteRecordInfo<'apps-questions-edit-id', '/apps/questions/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-questions-languages': RouteRecordInfo<'apps-questions-languages', '/apps/questions/languages', Record<never, never>, Record<never, never>>,
    'apps-questions-list': RouteRecordInfo<'apps-questions-list', '/apps/questions/list', Record<never, never>, Record<never, never>>,
    'apps-roles': RouteRecordInfo<'apps-roles', '/apps/roles', Record<never, never>, Record<never, never>>,
    'apps-sessions-live': RouteRecordInfo<'apps-sessions-live', '/apps/sessions/live', Record<never, never>, Record<never, never>>,
    'apps-sessions-monitor': RouteRecordInfo<'apps-sessions-monitor', '/apps/sessions/monitor', Record<never, never>, Record<never, never>>,
    'apps-system-actors': RouteRecordInfo<'apps-system-actors', '/apps/system/actors', Record<never, never>, Record<never, never>>,
    'apps-system-ai-settings': RouteRecordInfo<'apps-system-ai-settings', '/apps/system/ai-settings', Record<never, never>, Record<never, never>>,
    'apps-system-architecture': RouteRecordInfo<'apps-system-architecture', '/apps/system/architecture', Record<never, never>, Record<never, never>>,
    'apps-system-audit-log': RouteRecordInfo<'apps-system-audit-log', '/apps/system/audit-log', Record<never, never>, Record<never, never>>,
    'apps-system-dead-letters': RouteRecordInfo<'apps-system-dead-letters', '/apps/system/dead-letters', Record<never, never>, Record<never, never>>,
    'apps-system-embeddings': RouteRecordInfo<'apps-system-embeddings', '/apps/system/embeddings', Record<never, never>, Record<never, never>>,
    'apps-system-events': RouteRecordInfo<'apps-system-events', '/apps/system/events', Record<never, never>, Record<never, never>>,
    'apps-system-explanation-cache': RouteRecordInfo<'apps-system-explanation-cache', '/apps/system/explanation-cache', Record<never, never>, Record<never, never>>,
    'apps-system-health': RouteRecordInfo<'apps-system-health', '/apps/system/health', Record<never, never>, Record<never, never>>,
    'apps-system-settings': RouteRecordInfo<'apps-system-settings', '/apps/system/settings', Record<never, never>, Record<never, never>>,
    'apps-system-token-budget': RouteRecordInfo<'apps-system-token-budget', '/apps/system/token-budget', Record<never, never>, Record<never, never>>,
    'apps-tutoring-sessions': RouteRecordInfo<'apps-tutoring-sessions', '/apps/tutoring/sessions', Record<never, never>, Record<never, never>>,
    'apps-tutoring-sessions-id': RouteRecordInfo<'apps-tutoring-sessions-id', '/apps/tutoring/sessions/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-user-list': RouteRecordInfo<'apps-user-list', '/apps/user/list', Record<never, never>, Record<never, never>>,
    'apps-user-view-id': RouteRecordInfo<'apps-user-view-id', '/apps/user/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'dashboards-admin': RouteRecordInfo<'dashboards-admin', '/dashboards/admin', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'pages-account-settings-tab': RouteRecordInfo<'pages-account-settings-tab', '/pages/account-settings/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'privacy': RouteRecordInfo<'privacy', '/privacy', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'terms': RouteRecordInfo<'terms', '/terms', Record<never, never>, Record<never, never>>,
  }
}
