#!/usr/bin/env bash
# =============================================================================
# Cena — Stripe sandbox bootstrap (EPIC-PRR-I PRR-301)
#
# Creates the 3 Cena products + 6 recurring prices (ILS, VAT-inclusive) in
# your Stripe sandbox account via the `stripe` CLI, then writes a
# shell-sourceable env file with all the IDs ready for Cena.
#
# Prerequisites:
#   - `stripe` CLI installed (brew install stripe/stripe-cli/stripe)
#   - `stripe login` completed (auth token cached)
#   - `jq` installed (brew install jq)
#
# Usage:
#   ./scripts/stripe/bootstrap-sandbox.sh             # create + write .env
#   ./scripts/stripe/bootstrap-sandbox.sh --dry-run   # show commands, don't run
#   source .env.stripe.local                          # load IDs into shell
#
# The output file .env.stripe.local is gitignored (scripts/stripe/.gitignore).
# =============================================================================

set -euo pipefail

DRY_RUN=false
if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=true
fi

OUT_FILE=".env.stripe.local"

# ── sanity checks ────────────────────────────────────────────────────────
if ! command -v stripe >/dev/null 2>&1; then
  echo "error: stripe CLI not found. Install: brew install stripe/stripe-cli/stripe" >&2
  exit 1
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "error: jq not found. Install: brew install jq" >&2
  exit 1
fi

# Confirm we're in test mode (never run this against live keys).
MODE_CHECK=$(stripe config --list 2>&1 | grep -i "test_mode" || true)
if [[ -z "$MODE_CHECK" ]]; then
  # stripe CLI default is test mode; proceed.
  :
fi

# ── helpers ──────────────────────────────────────────────────────────────
run() {
  if $DRY_RUN; then
    echo "+ $*"
    # Return a placeholder so downstream jq doesn't fail in dry-run.
    echo '{"id":"DRY_RUN_ID"}'
  else
    eval "$@"
  fi
}

create_product() {
  local name="$1"
  echo "→ creating product: $name" >&2
  run "stripe products create --name '$name' --tax-code 'txcd_10000000'" | jq -r .id
}

create_price() {
  local product_id="$1" amount_agorot="$2" interval="$3" nickname="$4"
  echo "  → price ${interval} ₪$((amount_agorot/100)) ($nickname)" >&2
  run "stripe prices create \
    --product '$product_id' \
    --currency ils \
    --unit-amount $amount_agorot \
    -d 'recurring[interval]=$interval' \
    --tax-behavior inclusive \
    --nickname '$nickname'" | jq -r .id
}

# ── create products + prices ─────────────────────────────────────────────
echo "Creating Cena products in Stripe sandbox…"

BASIC_PRODUCT=$(create_product "Cena Basic")
BASIC_MONTHLY=$(create_price "$BASIC_PRODUCT" 7900    month "Basic Monthly ₪79")
BASIC_ANNUAL=$(create_price  "$BASIC_PRODUCT" 79000   year  "Basic Annual ₪790 (10-for-12)")

PLUS_PRODUCT=$(create_product "Cena Plus")
PLUS_MONTHLY=$(create_price  "$PLUS_PRODUCT"  22900   month "Plus Monthly ₪229")
PLUS_ANNUAL=$(create_price   "$PLUS_PRODUCT"  229000  year  "Plus Annual ₪2,290 (10-for-12)")

PREMIUM_PRODUCT=$(create_product "Cena Premium")
PREMIUM_MONTHLY=$(create_price "$PREMIUM_PRODUCT" 24900  month "Premium Monthly ₪249")
PREMIUM_ANNUAL=$(create_price  "$PREMIUM_PRODUCT" 249000 year  "Premium Annual ₪2,490 (10-for-12)")

# ── write env file ───────────────────────────────────────────────────────
if $DRY_RUN; then
  echo ""
  echo "Dry run complete — no products created, no env file written."
  exit 0
fi

cat >"$OUT_FILE" <<EOF
# Generated by scripts/stripe/bootstrap-sandbox.sh on $(date -u '+%Y-%m-%d %H:%M:%SZ')
# Source with: source $OUT_FILE
#
# SECRETS (STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET) are NOT in this file.
# Copy them yourself from the Stripe dashboard and export them alongside.
# Never commit this file (it is gitignored).

export Stripe__PriceIds__BasicMonthly="$BASIC_MONTHLY"
export Stripe__PriceIds__BasicAnnual="$BASIC_ANNUAL"
export Stripe__PriceIds__PlusMonthly="$PLUS_MONTHLY"
export Stripe__PriceIds__PlusAnnual="$PLUS_ANNUAL"
export Stripe__PriceIds__PremiumMonthly="$PREMIUM_MONTHLY"
export Stripe__PriceIds__PremiumAnnual="$PREMIUM_ANNUAL"
export Stripe__SuccessUrl="http://localhost:5175/subscription/confirm"
export Stripe__CancelUrl="http://localhost:5175/pricing"

# Remaining secrets — fill these in from your Stripe dashboard:
# export Stripe__SecretKey="sk_test_..."           # Developers → API keys
# export Stripe__WebhookSigningSecret="whsec_..."  # Developers → Webhooks (or from 'stripe listen')
EOF

echo ""
echo "✓ products + prices created in Stripe sandbox"
echo "✓ env file written: $OUT_FILE"
echo ""
echo "Next steps:"
echo "  1. Open $OUT_FILE, paste your STRIPE_SECRET_KEY + STRIPE_WEBHOOK_SECRET"
echo "  2. source $OUT_FILE"
echo "  3. In another terminal:  stripe listen --forward-to localhost:5050/api/webhooks/stripe"
echo "     (copy the 'whsec_...' it prints into Stripe__WebhookSigningSecret)"
echo "  4. Restart the student-api container; check logs for 'Stripe configured'."
