// =============================================================================
// Cena Platform -- Explanation Cache Service (L2)
// SAI-03: Redis-backed cache for misconception-specific explanations
//
// Key format: explain:{questionId}:{errorType}:{methodology}
// TTL: 30 days. Never throws on Redis failure — returns null (cache miss).
// =============================================================================

using System.Text.Json;
using Microsoft.Extensions.Logging;
using StackExchange.Redis;

namespace Cena.Actors.Services;

/// <summary>
/// A cached explanation previously generated by the LLM.
/// </summary>
public sealed record CachedExplanation(
    string Text,
    string ModelId,
    int TokenCount,
    DateTimeOffset GeneratedAt);

/// <summary>
/// Redis-backed cache for misconception-specific explanations.
/// All operations are safe: Redis failures result in cache misses, never exceptions.
/// </summary>
public interface IExplanationCacheService
{
    Task<CachedExplanation?> GetAsync(string questionId, string errorType, string methodology, CancellationToken ct);
    Task SetAsync(string questionId, string errorType, string methodology, CachedExplanation explanation, CancellationToken ct);
    Task InvalidateQuestionAsync(string questionId, CancellationToken ct);
}

public sealed class ExplanationCacheService : IExplanationCacheService
{
    private const string KeyPrefix = "explain";
    private static readonly TimeSpan CacheTtl = TimeSpan.FromDays(30);

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
    };

    private readonly IConnectionMultiplexer _redis;
    private readonly ILogger<ExplanationCacheService> _logger;

    public ExplanationCacheService(
        IConnectionMultiplexer redis,
        ILogger<ExplanationCacheService> logger)
    {
        _redis = redis;
        _logger = logger;
    }

    public async Task<CachedExplanation?> GetAsync(
        string questionId, string errorType, string methodology, CancellationToken ct)
    {
        try
        {
            var db = _redis.GetDatabase();
            var key = BuildKey(questionId, errorType, methodology);
            var value = await db.StringGetAsync(key);

            if (value.IsNullOrEmpty)
                return null;

            return JsonSerializer.Deserialize<CachedExplanation>(value!, JsonOptions);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex,
                "Redis cache GET failed for question {QuestionId}, error {ErrorType}. Treating as cache miss.",
                questionId, errorType);
            return null;
        }
    }

    public async Task SetAsync(
        string questionId, string errorType, string methodology,
        CachedExplanation explanation, CancellationToken ct)
    {
        try
        {
            var db = _redis.GetDatabase();
            var key = BuildKey(questionId, errorType, methodology);
            var json = JsonSerializer.Serialize(explanation, JsonOptions);
            await db.StringSetAsync(key, json, CacheTtl);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex,
                "Redis cache SET failed for question {QuestionId}, error {ErrorType}. Explanation not cached.",
                questionId, errorType);
        }
    }

    public async Task InvalidateQuestionAsync(string questionId, CancellationToken ct)
    {
        try
        {
            var server = GetServer();
            if (server is null) return;

            var db = _redis.GetDatabase();
            var pattern = $"{KeyPrefix}:{questionId}:*";

            await foreach (var key in server.KeysAsync(pattern: pattern))
            {
                await db.KeyDeleteAsync(key);
            }

            _logger.LogInformation("Invalidated explanation cache for question {QuestionId}", questionId);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex,
                "Redis cache invalidation failed for question {QuestionId}. Stale entries may persist until TTL.",
                questionId);
        }
    }

    private static string BuildKey(string questionId, string errorType, string methodology)
        => $"{KeyPrefix}:{questionId}:{errorType}:{methodology}";

    private IServer? GetServer()
    {
        try
        {
            var endpoints = _redis.GetEndPoints();
            return endpoints.Length > 0 ? _redis.GetServer(endpoints[0]) : null;
        }
        catch
        {
            return null;
        }
    }
}
