// =============================================================================
// Cena Platform -- Explanation Cache Service (L2)
// SAI-02: Redis-backed cache for error-type-specific explanations
//
// Key format: explain:{questionId}:{errorType}:{language}
// TTL: 30 days. Never throws on Redis failure -- returns null (cache miss).
//
// ExplanationErrorType is the domain-specific classification for caching.
// Most students make the same 3-5 categories of mistakes per question.
// After initial generation, ~80-90% of explanations are cache hits.
// =============================================================================

using System.Diagnostics.Metrics;
using System.Text.Json;
using Microsoft.Extensions.Logging;
using StackExchange.Redis;

namespace Cena.Actors.Services;

// =============================================================================
// EXPLANATION ERROR TYPE (domain-specific for L2 caching)
// =============================================================================

/// <summary>
/// Fine-grained error classification for explanation caching.
/// Maps a student's wrong answer to the underlying misconception category.
/// Each (questionId, errorType, language) tuple gets its own cached explanation.
/// </summary>
public enum ExplanationErrorType
{
    /// <summary>Wrong mental model of the concept.</summary>
    ConceptualMisunderstanding,

    /// <summary>Right concept, wrong execution of the procedure.</summary>
    ProceduralError,

    /// <summary>Understood the concept but made a sloppy mistake.</summary>
    CarelessMistake,

    /// <summary>No evidence of understanding -- random or uninformed choice.</summary>
    Guessing,

    /// <summary>Close to correct but missing a key step or detail.</summary>
    PartialUnderstanding
}

// =============================================================================
// CACHED EXPLANATION VALUE
// =============================================================================

/// <summary>
/// A cached explanation previously generated by the LLM.
/// </summary>
public sealed record CachedExplanation(
    string Text,
    string ModelId,
    int TokenCount,
    DateTimeOffset GeneratedAt);

// =============================================================================
// INTERFACE
// =============================================================================

/// <summary>
/// Redis-backed cache for error-type-specific explanations.
/// All operations are safe: Redis failures result in cache misses, never exceptions.
/// </summary>
public interface IExplanationCacheService
{
    /// <summary>Look up a cached explanation by (questionId, errorType, language).</summary>
    Task<CachedExplanation?> GetAsync(
        string questionId, ExplanationErrorType errorType, string language, CancellationToken ct);

    /// <summary>Store an explanation in the cache with 30-day TTL.</summary>
    Task SetAsync(
        string questionId, ExplanationErrorType errorType, string language,
        CachedExplanation explanation, CancellationToken ct);

    /// <summary>Invalidate all cached explanations for a question (e.g., when question is updated).</summary>
    Task InvalidateQuestionAsync(string questionId, CancellationToken ct);

    /// <summary>
    /// Legacy overload: look up by string errorType and methodology (backward-compatible).
    /// New code should prefer the ExplanationErrorType overload.
    /// </summary>
    Task<CachedExplanation?> GetAsync(
        string questionId, string errorType, string methodology, CancellationToken ct);

    /// <summary>
    /// Legacy overload: store by string errorType and methodology (backward-compatible).
    /// New code should prefer the ExplanationErrorType overload.
    /// </summary>
    Task SetAsync(
        string questionId, string errorType, string methodology,
        CachedExplanation explanation, CancellationToken ct);
}

// =============================================================================
// IMPLEMENTATION
// =============================================================================

public sealed class ExplanationCacheService : IExplanationCacheService
{
    private const string KeyPrefix = "explain";
    internal static readonly TimeSpan CacheTtl = TimeSpan.FromDays(30);

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
    };

    private readonly IConnectionMultiplexer _redis;
    private readonly ILogger<ExplanationCacheService> _logger;
    private readonly Counter<long> _cacheHitCounter;
    private readonly Counter<long> _cacheMissCounter;

    public ExplanationCacheService(
        IConnectionMultiplexer redis,
        ILogger<ExplanationCacheService> logger,
        IMeterFactory meterFactory)
    {
        _redis = redis;
        _logger = logger;

        var meter = meterFactory.Create("Cena.Actors.ExplanationCache", "1.0.0");
        _cacheHitCounter = meter.CreateCounter<long>(
            "cena.explanation_cache.hits_total",
            description: "Explanation cache hits (zero LLM cost)");
        _cacheMissCounter = meter.CreateCounter<long>(
            "cena.explanation_cache.misses_total",
            description: "Explanation cache misses (requires LLM generation)");
    }

    // ── Primary API: ExplanationErrorType + language ──

    public async Task<CachedExplanation?> GetAsync(
        string questionId, ExplanationErrorType errorType, string language, CancellationToken ct)
    {
        try
        {
            var db = _redis.GetDatabase();
            var key = BuildKey(questionId, errorType, language);
            var value = await db.StringGetAsync(key);

            if (value.IsNullOrEmpty)
            {
                _cacheMissCounter.Add(1,
                    new KeyValuePair<string, object?>("error_type", errorType.ToString()),
                    new KeyValuePair<string, object?>("language", language));
                return null;
            }

            _cacheHitCounter.Add(1,
                new KeyValuePair<string, object?>("error_type", errorType.ToString()),
                new KeyValuePair<string, object?>("language", language));

            return JsonSerializer.Deserialize<CachedExplanation>(value!, JsonOptions);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex,
                "Redis cache GET failed for question {QuestionId}, error {ErrorType}, language {Language}. Treating as cache miss.",
                questionId, errorType, language);
            return null;
        }
    }

    public async Task SetAsync(
        string questionId, ExplanationErrorType errorType, string language,
        CachedExplanation explanation, CancellationToken ct)
    {
        try
        {
            var db = _redis.GetDatabase();
            var key = BuildKey(questionId, errorType, language);
            var json = JsonSerializer.Serialize(explanation, JsonOptions);
            await db.StringSetAsync(key, json, CacheTtl);

            _logger.LogDebug(
                "Cached explanation for question {QuestionId}, error {ErrorType}, language {Language}, model {ModelId}",
                questionId, errorType, language, explanation.ModelId);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex,
                "Redis cache SET failed for question {QuestionId}, error {ErrorType}. Explanation not cached.",
                questionId, errorType);
        }
    }

    // ── Legacy API: string errorType + methodology (backward-compatible) ──

    public async Task<CachedExplanation?> GetAsync(
        string questionId, string errorType, string methodology, CancellationToken ct)
    {
        try
        {
            var db = _redis.GetDatabase();
            var key = BuildLegacyKey(questionId, errorType, methodology);
            var value = await db.StringGetAsync(key);

            if (value.IsNullOrEmpty)
                return null;

            return JsonSerializer.Deserialize<CachedExplanation>(value!, JsonOptions);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex,
                "Redis cache GET failed for question {QuestionId}, error {ErrorType}. Treating as cache miss.",
                questionId, errorType);
            return null;
        }
    }

    public async Task SetAsync(
        string questionId, string errorType, string methodology,
        CachedExplanation explanation, CancellationToken ct)
    {
        try
        {
            var db = _redis.GetDatabase();
            var key = BuildLegacyKey(questionId, errorType, methodology);
            var json = JsonSerializer.Serialize(explanation, JsonOptions);
            await db.StringSetAsync(key, json, CacheTtl);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex,
                "Redis cache SET failed for question {QuestionId}, error {ErrorType}. Explanation not cached.",
                questionId, errorType);
        }
    }

    // ── Invalidation ──

    public async Task InvalidateQuestionAsync(string questionId, CancellationToken ct)
    {
        try
        {
            var server = GetServer();
            if (server is null) return;

            var db = _redis.GetDatabase();
            var pattern = $"{KeyPrefix}:{questionId}:*";

            await foreach (var key in server.KeysAsync(pattern: pattern))
            {
                await db.KeyDeleteAsync(key);
            }

            _logger.LogInformation("Invalidated explanation cache for question {QuestionId}", questionId);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex,
                "Redis cache invalidation failed for question {QuestionId}. Stale entries may persist until TTL.",
                questionId);
        }
    }

    // ── Key Building ──

    /// <summary>
    /// SAI-02 key format: explain:{questionId}:{errorType}:{language}
    /// </summary>
    internal static string BuildKey(string questionId, ExplanationErrorType errorType, string language)
        => $"{KeyPrefix}:{questionId}:{errorType}:{language}";

    /// <summary>
    /// Legacy key format: explain:{questionId}:{errorType}:{methodology}
    /// Kept for backward compatibility with existing cached data.
    /// </summary>
    private static string BuildLegacyKey(string questionId, string errorType, string methodology)
        => $"{KeyPrefix}:{questionId}:{errorType}:{methodology}";

    private IServer? GetServer()
    {
        try
        {
            var endpoints = _redis.GetEndPoints();
            return endpoints.Length > 0 ? _redis.GetServer(endpoints[0]) : null;
        }
        catch
        {
            return null;
        }
    }
}
