// =============================================================================
// Cena Platform — Question Domain Events
// Event-sourced question lifecycle: creation, editing, quality gate, publishing
// Three creation paths: authored, ingested, AI-generated
// =============================================================================

namespace Cena.Actors.Events;

// ── Shared option data (used by creation + language version events) ──

public sealed record QuestionOptionData(
    string Label,
    string Text,
    string TextHtml,
    bool IsCorrect,
    string? DistractorRationale);

// ── Creation Events (3 paths) ──

/// <summary>Manually authored by a human (teacher, content creator).</summary>
public sealed record QuestionAuthored_V1(
    string QuestionId,
    string Stem,
    string StemHtml,
    IReadOnlyList<QuestionOptionData> Options,
    string Subject,
    string Topic,
    string Grade,
    int BloomsLevel,
    float Difficulty,
    IReadOnlyList<string> ConceptIds,
    string Language,
    string AuthorId,
    DateTimeOffset Timestamp,
    string? Explanation = null);

/// <summary>
/// V2 adds <see cref="LearningObjectiveId"/> per FIND-pedagogy-008.
/// Anderson &amp; Krathwohl (2001) + Wiggins &amp; McTighe (2005) require every
/// assessment item to trace to an explicit learning goal. Upcasted from V1
/// with a <c>null</c> LO id so existing streams replay cleanly.
/// </summary>
public sealed record QuestionAuthored_V2(
    string QuestionId,
    string Stem,
    string StemHtml,
    IReadOnlyList<QuestionOptionData> Options,
    string Subject,
    string Topic,
    string Grade,
    int BloomsLevel,
    float Difficulty,
    IReadOnlyList<string> ConceptIds,
    string Language,
    string AuthorId,
    DateTimeOffset Timestamp,
    string? Explanation,
    /// <summary>
    /// Learning-objective id this question assesses. Null means "unknown"
    /// (V1 event) and the projection logs a warning so curriculum authors
    /// can backfill.
    /// </summary>
    string? LearningObjectiveId);

/// <summary>Extracted from ingestion pipeline (OCR, document import).</summary>
public sealed record QuestionIngested_V1(
    string QuestionId,
    string Stem,
    string StemHtml,
    IReadOnlyList<QuestionOptionData> Options,
    string Subject,
    string Topic,
    string Grade,
    int BloomsLevel,
    float Difficulty,
    IReadOnlyList<string> ConceptIds,
    string Language,
    string SourceDocId,
    string SourceUrl,
    string SourceFilename,
    string? OriginalText,
    string ImportedBy,
    DateTimeOffset Timestamp,
    string? Explanation = null);

/// <summary>
/// V2 adds <see cref="LearningObjectiveId"/> per FIND-pedagogy-008.
/// Upcasted from V1 with a <c>null</c> LO id.
/// </summary>
public sealed record QuestionIngested_V2(
    string QuestionId,
    string Stem,
    string StemHtml,
    IReadOnlyList<QuestionOptionData> Options,
    string Subject,
    string Topic,
    string Grade,
    int BloomsLevel,
    float Difficulty,
    IReadOnlyList<string> ConceptIds,
    string Language,
    string SourceDocId,
    string SourceUrl,
    string SourceFilename,
    string? OriginalText,
    string ImportedBy,
    DateTimeOffset Timestamp,
    string? Explanation,
    string? LearningObjectiveId);

/// <summary>Generated by LLM. Stores full prompt/output for reproducibility.</summary>
public sealed record QuestionAiGenerated_V1(
    string QuestionId,
    string Stem,
    string StemHtml,
    IReadOnlyList<QuestionOptionData> Options,
    string Subject,
    string Topic,
    string Grade,
    int BloomsLevel,
    float Difficulty,
    IReadOnlyList<string> ConceptIds,
    string Language,
    string PromptText,
    string ModelId,
    float ModelTemperature,
    string RawModelOutput,
    string RequestedBy,
    string? Explanation,
    DateTimeOffset Timestamp);

/// <summary>
/// V2 adds <see cref="LearningObjectiveId"/> per FIND-pedagogy-008.
/// Upcasted from V1 with a <c>null</c> LO id.
/// </summary>
public sealed record QuestionAiGenerated_V2(
    string QuestionId,
    string Stem,
    string StemHtml,
    IReadOnlyList<QuestionOptionData> Options,
    string Subject,
    string Topic,
    string Grade,
    int BloomsLevel,
    float Difficulty,
    IReadOnlyList<string> ConceptIds,
    string Language,
    string PromptText,
    string ModelId,
    float ModelTemperature,
    string RawModelOutput,
    string RequestedBy,
    string? Explanation,
    DateTimeOffset Timestamp,
    string? LearningObjectiveId);

/// <summary>
/// Emitted when a learning-objective id is assigned to (or changed on)
/// an existing question after initial authoring — e.g., a curriculum author
/// backfills metadata on a V1 question that was created before
/// FIND-pedagogy-008 added the field. Separate event so the change is a
/// first-class entry in the audit history.
/// </summary>
public sealed record LearningObjectiveAssigned_V1(
    string QuestionId,
    string? PreviousObjectiveId,
    string NewObjectiveId,
    string AssignedBy,
    DateTimeOffset Timestamp);

// ── Edit Events ──

public sealed record QuestionStemEdited_V1(
    string QuestionId,
    string PreviousStem,
    string NewStem,
    string NewStemHtml,
    string EditedBy,
    DateTimeOffset Timestamp);

public sealed record QuestionOptionChanged_V1(
    string QuestionId,
    string OptionLabel,
    string PreviousText,
    string NewText,
    string? NewTextHtml,
    bool IsCorrect,
    string? DistractorRationale,
    string EditedBy,
    DateTimeOffset Timestamp);

public sealed record QuestionMetadataUpdated_V1(
    string QuestionId,
    string Field,
    string PreviousValue,
    string NewValue,
    string UpdatedBy,
    DateTimeOffset Timestamp);

// ── Quality Gate ──

/// <summary>Quality gate evaluation result stored as domain event for audit trail.</summary>
public sealed record QuestionQualityEvaluated_V1(
    string QuestionId,
    float CompositeScore,
    int FactualAccuracy,
    int LanguageQuality,
    int PedagogicalQuality,
    int DistractorQuality,
    int StemClarity,
    int BloomAlignment,
    int StructuralValidity,
    int CulturalSensitivity,
    string GateDecision,
    int ViolationCount,
    DateTimeOffset Timestamp);

// ── Lifecycle Events ──

public sealed record QuestionApproved_V1(
    string QuestionId,
    string ApprovedBy,
    DateTimeOffset Timestamp);

public sealed record QuestionPublished_V1(
    string QuestionId,
    string PublishedBy,
    DateTimeOffset Timestamp);

public sealed record QuestionDeprecated_V1(
    string QuestionId,
    string Reason,
    bool RemoveFromServing,
    string DeprecatedBy,
    DateTimeOffset Timestamp);

public sealed record QuestionForked_V1(
    string NewQuestionId,
    string SourceQuestionId,
    string ForkedBy,
    DateTimeOffset Timestamp);

// ── Figure Spec (FIGURE-002) ──

/// <summary>
/// FIGURE-002 — Sets or updates the figure specification on a question.
/// The spec is a polymorphic FigureSpec (function_plot, physics_diagram,
/// geometry, or raster). Null spec removes the figure.
/// </summary>
public sealed record QuestionFigureSpecUpdated_V1(
    string QuestionId,
    Cena.Infrastructure.Documents.FigureSpec? Spec,
    string UpdatedBy,
    DateTimeOffset UpdatedAt);

// ── Explanation ──

/// <summary>Adds or edits an explanation on any question (any creation path).</summary>
public sealed record ExplanationEdited_V1(
    string QuestionId,
    string? PreviousExplanation,
    string NewExplanation,
    string EditedBy,
    DateTimeOffset Timestamp);

/// <summary>Updates explanation via dedicated PATCH endpoint (SAI-001).</summary>
public sealed record QuestionExplanationUpdated_V1(
    string QuestionId,
    string Explanation,
    string UpdatedBy,
    DateTimeOffset UpdatedAt);

// ── Multi-Language ──

/// <summary>
/// FIND-pedagogy-013 — Adds a Hebrew/Arabic/English version to an existing question.
/// Includes per-locale explanation and distractor rationales.
/// </summary>
public sealed record LanguageVersionAdded_V1(
    string QuestionId,
    string Language,
    string Stem,
    string StemHtml,
    IReadOnlyList<QuestionOptionData> Options,
    string? Explanation,  // NEW
    IReadOnlyDictionary<string, string>? DistractorRationales,  // NEW - keyed by option label
    string TranslatedBy,
    DateTimeOffset Timestamp);

/// <summary>
/// FIND-pedagogy-013 — Adds or updates explanation for an existing language version.
/// Used for backfilling explanations without re-translating the entire question.
/// </summary>
public sealed record LanguageExplanationAdded_V1(
    string QuestionId,
    string Language,
    string Explanation,
    IReadOnlyDictionary<string, string>? DistractorRationales,
    string AddedBy,
    DateTimeOffset Timestamp);
