// =============================================================================
// Cena Platform — Question Domain Events
// Event-sourced question lifecycle: creation, editing, quality gate, publishing
// Three creation paths: authored, ingested, AI-generated
// =============================================================================

namespace Cena.Actors.Events;

// ── Shared option data (used by creation + language version events) ──

public sealed record QuestionOptionData(
    string Label,
    string Text,
    string TextHtml,
    bool IsCorrect,
    string? DistractorRationale);

// ── Creation Events (3 paths) ──

/// <summary>Manually authored by a human (teacher, content creator).</summary>
public sealed record QuestionAuthored_V1(
    string QuestionId,
    string Stem,
    string StemHtml,
    IReadOnlyList<QuestionOptionData> Options,
    string Subject,
    string Topic,
    string Grade,
    int BloomsLevel,
    float Difficulty,
    IReadOnlyList<string> ConceptIds,
    string Language,
    string AuthorId,
    DateTimeOffset Timestamp);

/// <summary>Extracted from ingestion pipeline (OCR, document import).</summary>
public sealed record QuestionIngested_V1(
    string QuestionId,
    string Stem,
    string StemHtml,
    IReadOnlyList<QuestionOptionData> Options,
    string Subject,
    string Topic,
    string Grade,
    int BloomsLevel,
    float Difficulty,
    IReadOnlyList<string> ConceptIds,
    string Language,
    string SourceDocId,
    string SourceUrl,
    string SourceFilename,
    string? OriginalText,
    string ImportedBy,
    DateTimeOffset Timestamp);

/// <summary>Generated by LLM. Stores full prompt/output for reproducibility.</summary>
public sealed record QuestionAiGenerated_V1(
    string QuestionId,
    string Stem,
    string StemHtml,
    IReadOnlyList<QuestionOptionData> Options,
    string Subject,
    string Topic,
    string Grade,
    int BloomsLevel,
    float Difficulty,
    IReadOnlyList<string> ConceptIds,
    string Language,
    string PromptText,
    string ModelId,
    float ModelTemperature,
    string RawModelOutput,
    string RequestedBy,
    string? Explanation,
    DateTimeOffset Timestamp);

// ── Edit Events ──

public sealed record QuestionStemEdited_V1(
    string QuestionId,
    string PreviousStem,
    string NewStem,
    string NewStemHtml,
    string EditedBy,
    DateTimeOffset Timestamp);

public sealed record QuestionOptionChanged_V1(
    string QuestionId,
    string OptionLabel,
    string PreviousText,
    string NewText,
    string? NewTextHtml,
    bool IsCorrect,
    string? DistractorRationale,
    string EditedBy,
    DateTimeOffset Timestamp);

public sealed record QuestionMetadataUpdated_V1(
    string QuestionId,
    string Field,
    string PreviousValue,
    string NewValue,
    string UpdatedBy,
    DateTimeOffset Timestamp);

// ── Quality Gate ──

/// <summary>Quality gate evaluation result stored as domain event for audit trail.</summary>
public sealed record QuestionQualityEvaluated_V1(
    string QuestionId,
    float CompositeScore,
    int FactualAccuracy,
    int LanguageQuality,
    int PedagogicalQuality,
    int DistractorQuality,
    int StemClarity,
    int BloomAlignment,
    int StructuralValidity,
    int CulturalSensitivity,
    string GateDecision,
    int ViolationCount,
    DateTimeOffset Timestamp);

// ── Lifecycle Events ──

public sealed record QuestionApproved_V1(
    string QuestionId,
    string ApprovedBy,
    DateTimeOffset Timestamp);

public sealed record QuestionPublished_V1(
    string QuestionId,
    string PublishedBy,
    DateTimeOffset Timestamp);

public sealed record QuestionDeprecated_V1(
    string QuestionId,
    string Reason,
    bool RemoveFromServing,
    string DeprecatedBy,
    DateTimeOffset Timestamp);

public sealed record QuestionForked_V1(
    string NewQuestionId,
    string SourceQuestionId,
    string ForkedBy,
    DateTimeOffset Timestamp);

// ── Explanation ──

/// <summary>Adds or edits an explanation on any question (any creation path).</summary>
public sealed record ExplanationEdited_V1(
    string QuestionId,
    string? PreviousExplanation,
    string NewExplanation,
    string EditedBy,
    DateTimeOffset Timestamp);

// ── Multi-Language ──

/// <summary>Adds a Hebrew/Arabic/English version to an existing question.</summary>
public sealed record LanguageVersionAdded_V1(
    string QuestionId,
    string Language,
    string Stem,
    string StemHtml,
    IReadOnlyList<QuestionOptionData> Options,
    string TranslatedBy,
    DateTimeOffset Timestamp);
