export default [
  { heading: 'Content' },
  {
    title: 'Ingestion Pipeline',
    icon: { icon: 'tabler-transfer-in' },
    to: 'apps-ingestion-pipeline',
    action: 'read',
    subject: 'Content',
  },
  {
    title: 'Moderation Queue',
    icon: { icon: 'tabler-checkbox' },
    to: 'apps-moderation-queue',
    action: 'read',
    subject: 'Content',
  },
  {
    title: 'Question Bank',
    icon: { icon: 'tabler-database' },
    to: 'apps-questions-list',
    action: 'read',
    subject: 'Questions',
  },

  { heading: 'Users' },
  {
    title: 'All Users',
    icon: { icon: 'tabler-users' },
    to: 'apps-user-list',
    action: 'read',
    subject: 'Users',
  },
  {
    title: 'Roles & Permissions',
    icon: { icon: 'tabler-lock' },
    children: [
      {
        title: 'Roles',
        to: 'apps-roles',
        action: 'read',
        subject: 'Users',
      },
      {
        title: 'Permissions',
        to: 'apps-permissions',
        action: 'read',
        subject: 'Users',
      },
    ],
    action: 'read',
    subject: 'Users',
  },

  { heading: 'Pedagogy' },
  {
    title: 'Methodology Analytics',
    icon: { icon: 'tabler-school' },
    to: 'apps-pedagogy-methodology',
    action: 'read',
    subject: 'Pedagogy',
  },
  {
    title: 'Cultural Context',
    icon: { icon: 'tabler-world' },
    to: 'apps-cultural-dashboard',
    action: 'read',
    subject: 'Pedagogy',
  },

  { heading: 'System' },
  {
    title: 'AI Providers',
    icon: { icon: 'tabler-sparkles' },
    to: 'apps-system-ai-settings',
    action: 'manage',
    subject: 'Settings',
  },
  {
    title: 'Actor Health',
    icon: { icon: 'tabler-heartbeat' },
    to: 'apps-system-health',
    action: 'read',
    subject: 'System',
  },
  {
    title: 'Actor Dashboard',
    icon: { icon: 'tabler-cpu' },
    to: 'apps-system-actors',
    action: 'read',
    subject: 'System',
  },
  {
    title: 'Architecture',
    icon: { icon: 'tabler-topology-star-3' },
    to: 'apps-system-architecture',
    action: 'read',
    subject: 'System',
  },
  {
    title: 'Event Stream',
    icon: { icon: 'tabler-activity' },
    to: 'apps-system-events',
    action: 'read',
    subject: 'System',
  },
  {
    title: 'Dead Letters',
    icon: { icon: 'tabler-mail-off' },
    to: 'apps-system-dead-letters',
    action: 'read',
    subject: 'System',
  },
  {
    title: 'Settings',
    icon: { icon: 'tabler-settings' },
    to: 'apps-system-settings',
    action: 'manage',
    subject: 'Settings',
  },
  {
    title: 'Audit Log',
    icon: { icon: 'tabler-file-analytics' },
    to: 'apps-system-audit-log',
    action: 'read',
    subject: 'AuditLog',
  },
  {
    title: 'Account Settings',
    icon: { icon: 'tabler-user-cog' },
    to: { name: 'pages-account-settings-tab', params: { tab: 'account' } },
  },
]
