"""OCR sidecar gRPC server (ADR-0033).

Serves three RPCs over port 50051:
    DetectLayoutAndRecognize  — Surya layout + Hebrew text OCR (Layer 1 + 2a)
    RecognizeMath             — pix2tex on a cropped math region (Layer 2b)
    Health                    — readiness probe (grpc_health.v1)

The two service modules are loaded lazily so the server can report
NOT_READY while models are still warming. prewarm.py is expected to run
as an init-container in production — this server will still boot without
it, just with a longer first-request latency.

Proto definitions live in ocr.proto; generated stubs are produced at
Docker build time (see Dockerfile) — in a local dev run invoke:
    python -m grpc_tools.protoc -I=app --python_out=app \\
        --grpc_python_out=app app/ocr.proto
"""
from __future__ import annotations

import logging
import os
import signal
import sys
import time
from concurrent import futures

import grpc
from grpc_health.v1 import health, health_pb2, health_pb2_grpc
from grpc_reflection.v1alpha import reflection

logging.basicConfig(
    level=os.environ.get("OCR_SIDECAR_LOG_LEVEL", "INFO"),
    format="%(asctime)s %(levelname)s [%(name)s] %(message)s",
)
log = logging.getLogger("ocr-sidecar")


def build_server() -> grpc.Server:
    port = int(os.environ.get("OCR_SIDECAR_PORT", "50051"))
    max_workers = int(os.environ.get("OCR_SIDECAR_WORKERS", "4"))

    server = grpc.server(
        futures.ThreadPoolExecutor(max_workers=max_workers),
        options=[
            ("grpc.max_send_message_length", 50 * 1024 * 1024),
            ("grpc.max_receive_message_length", 50 * 1024 * 1024),
        ],
    )

    # Health service for K8s probes
    health_servicer = health.HealthServicer()
    health_pb2_grpc.add_HealthServicer_to_server(health_servicer, server)
    health_servicer.set("", health_pb2.HealthCheckResponse.NOT_SERVING)

    # OcrSidecar service — lazy-loaded; marks health SERVING once models warm
    try:
        from ocr_pb2_grpc import add_OcrSidecarServicer_to_server  # generated by protoc
        from surya_service import SuryaService
        from pix2tex_service import Pix2TexService

        class Sidecar:
            def __init__(self) -> None:
                self.surya = SuryaService()
                self.pix2tex = Pix2TexService()

            def DetectLayoutAndRecognize(self, request, context):
                return self.surya.recognize(request, context)

            def RecognizeMath(self, request, context):
                return self.pix2tex.recognize(request, context)

            def Health(self, request, context):
                from ocr_pb2 import HealthResponse
                surya_ok = self.surya.is_ready()
                pix_ok = self.pix2tex.is_ready()
                if surya_ok and pix_ok:
                    status = HealthResponse.Status.SERVING
                elif surya_ok or pix_ok:
                    status = HealthResponse.Status.DEGRADED
                else:
                    status = HealthResponse.Status.NOT_READY
                return HealthResponse(
                    status=status,
                    message="ok" if surya_ok and pix_ok else "models loading",
                    surya_loaded=surya_ok,
                    pix2tex_loaded=pix_ok,
                )

        add_OcrSidecarServicer_to_server(Sidecar(), server)
        health_servicer.set("", health_pb2.HealthCheckResponse.SERVING)
        log.info("OcrSidecar service registered")

        # Reflection for grpcurl debugging
        import ocr_pb2
        reflection.enable_server_reflection(
            (ocr_pb2.DESCRIPTOR.services_by_name["OcrSidecar"].full_name,
             health_pb2.DESCRIPTOR.services_by_name["Health"].full_name,
             reflection.SERVICE_NAME),
            server,
        )
    except ModuleNotFoundError as e:
        # Stubs not yet generated — allow the server to boot in degraded
        # mode so `docker build` + `docker run` smoke-test is possible
        # before Grpc.Tools runs.
        log.warning("OcrSidecar servicer not registered (%s) — health will stay NOT_SERVING", e)
    except Exception as e:  # noqa: BLE001
        log.exception("Failed to register OcrSidecar servicer: %s", e)

    server.add_insecure_port(f"[::]:{port}")
    log.info("gRPC server listening on :%d (workers=%d)", port, max_workers)
    return server


def main() -> int:
    server = build_server()
    server.start()

    def shutdown(signum, _frame):
        log.info("signal %d received — graceful stop", signum)
        grace = int(os.environ.get("OCR_SIDECAR_GRACE_SECONDS", "20"))
        stopped = server.stop(grace=grace)
        stopped.wait(timeout=grace + 5)
        sys.exit(0)

    signal.signal(signal.SIGTERM, shutdown)
    signal.signal(signal.SIGINT, shutdown)

    try:
        while True:
            time.sleep(3600)
    except KeyboardInterrupt:
        shutdown(signal.SIGINT, None)
    return 0


if __name__ == "__main__":
    sys.exit(main())
