// =============================================================================
// Cena Platform -- Bagrut Concept Catalog (read-only curriculum data)
// The Israeli Bagrut 5-unit syllabus encoded as a static lookup table.
// Used by MasteryTrackingService to project student mastery records
// through a real curriculum graph.
// =============================================================================

namespace Cena.Admin.Api;

/// <summary>
/// Canonical curriculum graph. Not a stub — this is real subject-matter
/// data taken from the Israeli Bagrut 5-unit syllabus. Used to project
/// raw mastery events into admin-dashboard-ready concept nodes.
/// </summary>
internal static class BagrutConceptCatalog
{
    public readonly record struct ConceptEntry(
        string Id,
        string Name,
        string Subject,
        string Cluster,
        IReadOnlyList<string> Prereqs,
        IReadOnlyList<string> Unlocks);

    public static readonly IReadOnlyList<ConceptEntry> All = new ConceptEntry[]
    {
        // ── MATH ──
        new("M-ALG-01","Number Properties","Math","algebra",Array.Empty<string>(),new[]{"M-ALG-02","M-ALG-03","M-FUN-01","M-PRB-01"}),
        new("M-ALG-02","Linear Equations","Math","algebra",new[]{"M-ALG-01"},new[]{"M-ALG-04","M-ALG-05","M-GEO-04","P-KIN-01"}),
        new("M-ALG-03","Inequalities","Math","algebra",new[]{"M-ALG-01"},Array.Empty<string>()),
        new("M-ALG-04","Quadratic Equations","Math","algebra",new[]{"M-ALG-02"},new[]{"M-ALG-06","M-ALG-08","M-FUN-03","P-KIN-03"}),
        new("M-ALG-05","Systems of Equations","Math","algebra",new[]{"M-ALG-02"},new[]{"P-DYN-03","C-EQU-01"}),
        new("M-ALG-06","Polynomials","Math","algebra",new[]{"M-ALG-04"},new[]{"M-ALG-07","M-CAL-01"}),
        new("M-ALG-07","Rational Expressions","Math","algebra",new[]{"M-ALG-06"},Array.Empty<string>()),
        new("M-ALG-08","Sequences & Series","Math","algebra",new[]{"M-ALG-04"},new[]{"M-PRB-04","B-POP-02"}),
        new("M-FUN-01","Function Basics","Math","functions",new[]{"M-ALG-01"},new[]{"M-FUN-02"}),
        new("M-FUN-02","Linear Functions","Math","functions",new[]{"M-FUN-01"},new[]{"M-FUN-03","M-FUN-04","M-FUN-07","M-GEO-07","P-KIN-02"}),
        new("M-FUN-03","Quadratic Functions","Math","functions",new[]{"M-ALG-04","M-FUN-02"},new[]{"M-FUN-06","M-CAL-01","P-KIN-03"}),
        new("M-FUN-04","Exponential Functions","Math","functions",new[]{"M-FUN-02"},new[]{"M-FUN-05","M-FUN-06","C-RAT-01","B-POP-02"}),
        new("M-FUN-05","Logarithmic Functions","Math","functions",new[]{"M-FUN-04"},new[]{"C-PH-01"}),
        new("M-FUN-06","Composite Functions","Math","functions",new[]{"M-FUN-03","M-FUN-04"},Array.Empty<string>()),
        new("M-FUN-07","Inverse Functions","Math","functions",new[]{"M-FUN-02"},Array.Empty<string>()),
        new("M-GEO-01","Angles & Lines","Math","geometry",Array.Empty<string>(),new[]{"M-GEO-02","M-GEO-04","P-OPT-01"}),
        new("M-GEO-02","Triangles","Math","geometry",new[]{"M-GEO-01"},new[]{"M-GEO-03","M-GEO-05","M-GEO-06"}),
        new("M-GEO-03","Circle Properties","Math","geometry",new[]{"M-GEO-02"},new[]{"P-CIR-01"}),
        new("M-GEO-04","Coordinate Geometry","Math","geometry",new[]{"M-GEO-01","M-ALG-02"},new[]{"M-GEO-07","M-VEC-01"}),
        new("M-GEO-05","Trigonometric Ratios","Math","geometry",new[]{"M-GEO-02"},new[]{"M-TRG-01","M-TRG-03","M-TRG-04"}),
        new("M-GEO-06","Area & Volume","Math","geometry",new[]{"M-GEO-02"},new[]{"P-FLU-01","C-STO-02"}),
        new("M-GEO-07","Analytic Geometry","Math","geometry",new[]{"M-GEO-04","M-FUN-02"},Array.Empty<string>()),
        new("M-TRG-01","Trig Identities","Math","trigonometry",new[]{"M-GEO-05"},new[]{"M-TRG-02","M-TRG-03","M-VEC-01","P-WAV-02"}),
        new("M-TRG-02","Trig Equations","Math","trigonometry",new[]{"M-TRG-01"},Array.Empty<string>()),
        new("M-TRG-03","Sine & Cosine Rules","Math","trigonometry",new[]{"M-GEO-05","M-TRG-01"},new[]{"P-WAV-02"}),
        new("M-TRG-04","Radian Measure","Math","trigonometry",new[]{"M-GEO-05"},new[]{"P-CIR-01"}),
        new("M-CAL-01","Limits","Math","calculus",new[]{"M-FUN-03","M-ALG-06"},new[]{"M-CAL-02"}),
        new("M-CAL-02","Derivative Definition","Math","calculus",new[]{"M-CAL-01"},new[]{"M-CAL-03"}),
        new("M-CAL-03","Derivative Rules","Math","calculus",new[]{"M-CAL-02"},new[]{"M-CAL-04","M-CAL-05","P-KIN-04","C-RAT-02"}),
        new("M-CAL-04","Applications of Derivatives","Math","calculus",new[]{"M-CAL-03"},new[]{"P-DYN-02"}),
        new("M-CAL-05","Integrals Intro","Math","calculus",new[]{"M-CAL-03"},new[]{"M-CAL-06","P-ENE-02"}),
        new("M-CAL-06","Definite Integrals","Math","calculus",new[]{"M-CAL-05"},Array.Empty<string>()),
        new("M-PRB-01","Counting Principles","Math","probability",new[]{"M-ALG-01"},new[]{"M-PRB-02"}),
        new("M-PRB-02","Basic Probability","Math","probability",new[]{"M-PRB-01"},new[]{"M-PRB-03","B-GEN-03"}),
        new("M-PRB-03","Conditional Probability","Math","probability",new[]{"M-PRB-02"},new[]{"M-PRB-04"}),
        new("M-PRB-04","Binomial Distribution","Math","probability",new[]{"M-PRB-03","M-ALG-08"},new[]{"M-PRB-05","B-POP-03"}),
        new("M-PRB-05","Normal Distribution","Math","probability",new[]{"M-PRB-04"},new[]{"M-PRB-06"}),
        new("M-PRB-06","Statistical Inference","Math","probability",new[]{"M-PRB-05"},Array.Empty<string>()),
        new("M-VEC-01","Vector Basics","Math","vectors",new[]{"M-GEO-04","M-TRG-01"},new[]{"M-VEC-02","P-DYN-01"}),
        new("M-VEC-02","Dot Product","Math","vectors",new[]{"M-VEC-01"},new[]{"M-VEC-03","M-VEC-04","P-ENE-01"}),
        new("M-VEC-03","Cross Product","Math","vectors",new[]{"M-VEC-02"},new[]{"P-MAG-01"}),
        new("M-VEC-04","Vector Applications","Math","vectors",new[]{"M-VEC-02"},Array.Empty<string>()),

        // ── PHYSICS ──
        new("P-KIN-01","Displacement & Velocity","Physics","kinematics",new[]{"M-ALG-02"},new[]{"P-KIN-02","P-KIN-03"}),
        new("P-KIN-02","Uniform Motion Graphs","Physics","kinematics",new[]{"P-KIN-01","M-FUN-02"},new[]{"P-KIN-04"}),
        new("P-KIN-03","Projectile Motion","Physics","kinematics",new[]{"P-KIN-01","M-ALG-04","M-FUN-03"},new[]{"P-DYN-01"}),
        new("P-KIN-04","Acceleration & Calculus","Physics","kinematics",new[]{"P-KIN-02","M-CAL-03"},new[]{"P-DYN-02"}),
        new("P-DYN-01","Newton's Laws","Physics","dynamics",new[]{"P-KIN-03","M-VEC-01"},new[]{"P-DYN-02","P-DYN-03","P-CIR-01"}),
        new("P-DYN-02","Force & Acceleration","Physics","dynamics",new[]{"P-DYN-01","P-KIN-04","M-CAL-04"},new[]{"P-ENE-01"}),
        new("P-DYN-03","Equilibrium & Statics","Physics","dynamics",new[]{"P-DYN-01","M-ALG-05"},Array.Empty<string>()),
        new("P-ENE-01","Work & Kinetic Energy","Physics","energy",new[]{"P-DYN-02","M-VEC-02"},new[]{"P-ENE-02","P-ENE-03"}),
        new("P-ENE-02","Potential Energy & Conservation","Physics","energy",new[]{"P-ENE-01","M-CAL-05"},new[]{"P-MOM-01","C-THR-01"}),
        new("P-ENE-03","Power & Efficiency","Physics","energy",new[]{"P-ENE-01"},Array.Empty<string>()),
        new("P-MOM-01","Linear Momentum","Physics","momentum",new[]{"P-ENE-02"},new[]{"P-MOM-02"}),
        new("P-MOM-02","Collisions & Impulse","Physics","momentum",new[]{"P-MOM-01"},Array.Empty<string>()),
        new("P-CIR-01","Circular Motion","Physics","circular-motion",new[]{"P-DYN-01","M-GEO-03","M-TRG-04"},new[]{"P-GRV-01"}),
        new("P-GRV-01","Gravitation","Physics","gravitation",new[]{"P-CIR-01"},Array.Empty<string>()),
        new("P-WAV-01","Wave Properties","Physics","waves",Array.Empty<string>(),new[]{"P-WAV-02","P-WAV-03"}),
        new("P-WAV-02","Wave Mathematics","Physics","waves",new[]{"P-WAV-01","M-TRG-01","M-TRG-03"},new[]{"P-OPT-02","P-SND-01"}),
        new("P-WAV-03","Standing Waves","Physics","waves",new[]{"P-WAV-01"},Array.Empty<string>()),
        new("P-SND-01","Sound Waves","Physics","waves",new[]{"P-WAV-02"},Array.Empty<string>()),
        new("P-OPT-01","Reflection & Refraction","Physics","optics",new[]{"M-GEO-01"},new[]{"P-OPT-02"}),
        new("P-OPT-02","Lenses & Mirrors","Physics","optics",new[]{"P-OPT-01","P-WAV-02"},Array.Empty<string>()),
        new("P-ELC-01","Electric Charge & Field","Physics","electricity",Array.Empty<string>(),new[]{"P-ELC-02","P-ELC-03"}),
        new("P-ELC-02","Ohm's Law & Circuits","Physics","electricity",new[]{"P-ELC-01"},new[]{"P-ELC-04","C-ELE-01"}),
        new("P-ELC-03","Electric Potential","Physics","electricity",new[]{"P-ELC-01"},new[]{"P-ELC-04"}),
        new("P-ELC-04","Capacitors","Physics","electricity",new[]{"P-ELC-02","P-ELC-03"},Array.Empty<string>()),
        new("P-MAG-01","Magnetic Fields","Physics","magnetism",new[]{"M-VEC-03"},new[]{"P-MAG-02"}),
        new("P-MAG-02","Electromagnetic Induction","Physics","magnetism",new[]{"P-MAG-01"},Array.Empty<string>()),
        new("P-FLU-01","Pressure & Buoyancy","Physics","fluids",new[]{"M-GEO-06"},Array.Empty<string>()),
        new("P-MOD-01","Photoelectric Effect","Physics","modern",Array.Empty<string>(),new[]{"P-MOD-02"}),
        new("P-MOD-02","Wave-Particle Duality","Physics","modern",new[]{"P-MOD-01"},new[]{"P-MOD-03"}),
        new("P-MOD-03","Atomic Models","Physics","modern",new[]{"P-MOD-02"},new[]{"C-ATM-01"}),

        // ── CHEMISTRY ──
        new("C-ATM-01","Electron Configuration","Chemistry","atomic",new[]{"P-MOD-03"},new[]{"C-ATM-02","C-BND-01"}),
        new("C-ATM-02","Periodic Trends","Chemistry","atomic",new[]{"C-ATM-01"},new[]{"C-BND-01","C-BND-02"}),
        new("C-BND-01","Ionic Bonding","Chemistry","bonding",new[]{"C-ATM-01","C-ATM-02"},new[]{"C-STO-01","C-SOL-01"}),
        new("C-BND-02","Covalent Bonding","Chemistry","bonding",new[]{"C-ATM-02"},new[]{"C-BND-03","C-ORG-01"}),
        new("C-BND-03","Intermolecular Forces","Chemistry","bonding",new[]{"C-BND-02"},new[]{"C-SOL-01","C-THR-02"}),
        new("C-STO-01","Moles & Molar Mass","Chemistry","stoichiometry",new[]{"C-BND-01"},new[]{"C-STO-02","C-STO-03"}),
        new("C-STO-02","Gas Laws","Chemistry","stoichiometry",new[]{"C-STO-01","M-GEO-06"},new[]{"C-THR-01"}),
        new("C-STO-03","Reaction Stoichiometry","Chemistry","stoichiometry",new[]{"C-STO-01"},new[]{"C-EQU-01","C-RAT-01"}),
        new("C-THR-01","Enthalpy & Hess's Law","Chemistry","thermochemistry",new[]{"C-STO-02","P-ENE-02"},new[]{"C-THR-02"}),
        new("C-THR-02","Entropy & Free Energy","Chemistry","thermochemistry",new[]{"C-THR-01","C-BND-03"},Array.Empty<string>()),
        new("C-EQU-01","Chemical Equilibrium","Chemistry","equilibrium",new[]{"C-STO-03","M-ALG-05"},new[]{"C-EQU-02","C-ACB-01"}),
        new("C-EQU-02","Le Chatelier's Principle","Chemistry","equilibrium",new[]{"C-EQU-01"},Array.Empty<string>()),
        new("C-ACB-01","Acids, Bases & pH","Chemistry","acids-bases",new[]{"C-EQU-01"},new[]{"C-ACB-02"}),
        new("C-ACB-02","Titrations & Buffers","Chemistry","acids-bases",new[]{"C-ACB-01"},Array.Empty<string>()),
        new("C-PH-01","pH Calculations","Chemistry","acids-bases",new[]{"C-ACB-01","M-FUN-05"},Array.Empty<string>()),
        new("C-RAT-01","Rate Laws","Chemistry","kinetics",new[]{"C-STO-03","M-FUN-04"},new[]{"C-RAT-02"}),
        new("C-RAT-02","Activation Energy","Chemistry","kinetics",new[]{"C-RAT-01","M-CAL-03"},Array.Empty<string>()),
        new("C-ELE-01","Galvanic Cells","Chemistry","electrochemistry",new[]{"P-ELC-02"},new[]{"C-ELE-02"}),
        new("C-ELE-02","Electrolysis","Chemistry","electrochemistry",new[]{"C-ELE-01"},Array.Empty<string>()),
        new("C-ORG-01","Hydrocarbons","Chemistry","organic",new[]{"C-BND-02"},new[]{"C-ORG-02","C-ORG-03"}),
        new("C-ORG-02","Functional Groups","Chemistry","organic",new[]{"C-ORG-01"},new[]{"C-ORG-04","B-MOL-01"}),
        new("C-ORG-03","Isomerism","Chemistry","organic",new[]{"C-ORG-01"},Array.Empty<string>()),
        new("C-ORG-04","Polymers","Chemistry","organic",new[]{"C-ORG-02"},new[]{"B-MOL-02"}),
        new("C-SOL-01","Solubility & Concentration","Chemistry","solutions",new[]{"C-BND-01","C-BND-03"},Array.Empty<string>()),

        // ── BIOLOGY ──
        new("B-CEL-01","Cell Structure","Biology","cell-biology",Array.Empty<string>(),new[]{"B-CEL-02","B-CEL-03","B-CEL-04"}),
        new("B-CEL-02","Cell Membrane & Transport","Biology","cell-biology",new[]{"B-CEL-01"},new[]{"B-PHY-01","B-NRV-01"}),
        new("B-CEL-03","Mitosis & Cell Cycle","Biology","cell-biology",new[]{"B-CEL-01"},new[]{"B-GEN-01","B-CEL-05"}),
        new("B-CEL-04","Cell Respiration","Biology","cell-biology",new[]{"B-CEL-01"},new[]{"B-PHO-01","B-PHY-02"}),
        new("B-CEL-05","Meiosis","Biology","cell-biology",new[]{"B-CEL-03"},new[]{"B-GEN-02"}),
        new("B-MOL-01","DNA Structure & Replication","Biology","molecular",new[]{"C-ORG-02"},new[]{"B-MOL-02","B-MOL-03"}),
        new("B-MOL-02","Protein Synthesis","Biology","molecular",new[]{"B-MOL-01","C-ORG-04"},new[]{"B-MOL-04","B-GEN-01"}),
        new("B-MOL-03","Gene Regulation","Biology","molecular",new[]{"B-MOL-01"},new[]{"B-BIO-01"}),
        new("B-MOL-04","Mutations","Biology","molecular",new[]{"B-MOL-02"},new[]{"B-EVO-02","B-GEN-03"}),
        new("B-GEN-01","Mendelian Genetics","Biology","genetics",new[]{"B-CEL-03","B-MOL-02"},new[]{"B-GEN-02","B-GEN-03"}),
        new("B-GEN-02","Meiosis & Crossing Over","Biology","genetics",new[]{"B-GEN-01","B-CEL-05"},new[]{"B-GEN-04"}),
        new("B-GEN-03","Pedigree & Probability","Biology","genetics",new[]{"B-GEN-01","B-MOL-04","M-PRB-02"},new[]{"B-GEN-04"}),
        new("B-GEN-04","Population Genetics","Biology","genetics",new[]{"B-GEN-02","B-GEN-03"},new[]{"B-EVO-01"}),
        new("B-EVO-01","Natural Selection","Biology","evolution",new[]{"B-GEN-04"},new[]{"B-EVO-02","B-ECO-01"}),
        new("B-EVO-02","Speciation","Biology","evolution",new[]{"B-EVO-01","B-MOL-04"},Array.Empty<string>()),
        new("B-ECO-01","Ecosystems & Energy Flow","Biology","ecology",new[]{"B-EVO-01"},new[]{"B-ECO-02","B-POP-01"}),
        new("B-ECO-02","Biogeochemical Cycles","Biology","ecology",new[]{"B-ECO-01"},Array.Empty<string>()),
        new("B-POP-01","Population Dynamics","Biology","ecology",new[]{"B-ECO-01"},new[]{"B-POP-02","B-POP-03"}),
        new("B-POP-02","Growth Models","Biology","ecology",new[]{"B-POP-01","M-FUN-04","M-ALG-08"},Array.Empty<string>()),
        new("B-POP-03","Community Ecology","Biology","ecology",new[]{"B-POP-01","M-PRB-04"},Array.Empty<string>()),
        new("B-PHO-01","Light Reactions","Biology","photosynthesis",new[]{"B-CEL-04"},new[]{"B-PHO-02"}),
        new("B-PHO-02","Calvin Cycle","Biology","photosynthesis",new[]{"B-PHO-01"},Array.Empty<string>()),
        new("B-PHY-01","Nervous System","Biology","physiology",new[]{"B-CEL-02"},new[]{"B-NRV-01"}),
        new("B-NRV-01","Action Potential","Biology","physiology",new[]{"B-PHY-01","B-CEL-02"},new[]{"B-NRV-02"}),
        new("B-NRV-02","Synapse & Neurotransmitters","Biology","physiology",new[]{"B-NRV-01"},Array.Empty<string>()),
        new("B-PHY-02","Endocrine System","Biology","physiology",new[]{"B-CEL-04"},new[]{"B-IMM-01"}),
        new("B-IMM-01","Immune System","Biology","immunology",new[]{"B-PHY-02"},new[]{"B-IMM-02"}),
        new("B-IMM-02","Adaptive Immunity","Biology","immunology",new[]{"B-IMM-01"},Array.Empty<string>()),
        new("B-BIO-01","PCR & Gel Electrophoresis","Biology","biotechnology",new[]{"B-MOL-03"},new[]{"B-BIO-02"}),
        new("B-BIO-02","Genetic Engineering","Biology","biotechnology",new[]{"B-BIO-01"},Array.Empty<string>()),

        // ── COMPUTER SCIENCE ──
        new("CS-FND-01","Variables & Data Types","CS","fundamentals",Array.Empty<string>(),new[]{"CS-FND-02","CS-FND-03"}),
        new("CS-FND-02","Control Flow","CS","fundamentals",new[]{"CS-FND-01"},new[]{"CS-FND-04","CS-ALG-01"}),
        new("CS-FND-03","Arrays & Strings","CS","fundamentals",new[]{"CS-FND-01"},new[]{"CS-FND-04","CS-DST-01"}),
        new("CS-FND-04","Functions & Scope","CS","fundamentals",new[]{"CS-FND-02","CS-FND-03"},new[]{"CS-OOP-01","CS-REC-01"}),
        new("CS-OOP-01","Classes & Objects","CS","oop",new[]{"CS-FND-04"},new[]{"CS-OOP-02","CS-OOP-03"}),
        new("CS-OOP-02","Inheritance & Polymorphism","CS","oop",new[]{"CS-OOP-01"},new[]{"CS-OOP-04"}),
        new("CS-OOP-03","Encapsulation & Abstraction","CS","oop",new[]{"CS-OOP-01"},Array.Empty<string>()),
        new("CS-OOP-04","Design Patterns Intro","CS","oop",new[]{"CS-OOP-02"},Array.Empty<string>()),
        new("CS-ALG-01","Linear & Binary Search","CS","algorithms",new[]{"CS-FND-02"},new[]{"CS-ALG-02","CS-ALG-03"}),
        new("CS-ALG-02","Sorting Algorithms","CS","algorithms",new[]{"CS-ALG-01"},new[]{"CS-CMP-01"}),
        new("CS-ALG-03","Greedy Algorithms","CS","algorithms",new[]{"CS-ALG-01"},new[]{"CS-DYN-01"}),
        new("CS-DST-01","Linked Lists","CS","data-structures",new[]{"CS-FND-03"},new[]{"CS-DST-02","CS-DST-03"}),
        new("CS-DST-02","Stacks & Queues","CS","data-structures",new[]{"CS-DST-01"},new[]{"CS-GRP-01"}),
        new("CS-DST-03","Trees & BST","CS","data-structures",new[]{"CS-DST-01"},new[]{"CS-DST-04","CS-GRP-01"}),
        new("CS-DST-04","Hash Tables","CS","data-structures",new[]{"CS-DST-03"},Array.Empty<string>()),
        new("CS-REC-01","Recursion Basics","CS","recursion",new[]{"CS-FND-04"},new[]{"CS-REC-02","CS-DYN-01"}),
        new("CS-REC-02","Backtracking","CS","recursion",new[]{"CS-REC-01"},Array.Empty<string>()),
        new("CS-CMP-01","Big-O Analysis","CS","complexity",new[]{"CS-ALG-02"},new[]{"CS-CMP-02"}),
        new("CS-CMP-02","Space vs Time Trade-offs","CS","complexity",new[]{"CS-CMP-01"},Array.Empty<string>()),
        new("CS-GRP-01","BFS & DFS","CS","graphs",new[]{"CS-DST-02","CS-DST-03"},new[]{"CS-GRP-02"}),
        new("CS-GRP-02","Shortest Path (Dijkstra)","CS","graphs",new[]{"CS-GRP-01"},Array.Empty<string>()),
        new("CS-DYN-01","Memoization & Tabulation","CS","dynamic-programming",new[]{"CS-ALG-03","CS-REC-01"},Array.Empty<string>()),
        new("CS-BOL-01","Boolean Algebra","CS","logic",Array.Empty<string>(),new[]{"CS-BOL-02"}),
        new("CS-BOL-02","Logic Gates & Circuits","CS","logic",new[]{"CS-BOL-01"},Array.Empty<string>()),
        new("CS-DB-01","Relational Model & SQL","CS","databases",new[]{"CS-FND-03"},Array.Empty<string>()),

        // ── ENGLISH ──
        new("E-RDG-01","Reading Comprehension Basics","English","reading",Array.Empty<string>(),new[]{"E-RDG-02","E-RDG-03"}),
        new("E-RDG-02","Inference & Analysis","English","reading",new[]{"E-RDG-01"},new[]{"E-RDG-04","E-LIT-01"}),
        new("E-RDG-03","Unseen Text Strategies","English","reading",new[]{"E-RDG-01"},new[]{"E-RDG-04"}),
        new("E-RDG-04","Rhetoric & Persuasion","English","reading",new[]{"E-RDG-02","E-RDG-03"},new[]{"E-WRT-03"}),
        new("E-GRM-01","Tenses & Verb Forms","English","grammar",Array.Empty<string>(),new[]{"E-GRM-02","E-GRM-03"}),
        new("E-GRM-02","Conditionals & Modals","English","grammar",new[]{"E-GRM-01"},new[]{"E-WRT-01"}),
        new("E-GRM-03","Relative Clauses","English","grammar",new[]{"E-GRM-01"},new[]{"E-WRT-01"}),
        new("E-VOC-01","Academic Vocabulary","English","vocabulary",Array.Empty<string>(),new[]{"E-VOC-02","E-WRT-01"}),
        new("E-VOC-02","Context Clues & Word Formation","English","vocabulary",new[]{"E-VOC-01"},Array.Empty<string>()),
        new("E-WRT-01","Essay Structure","English","writing",new[]{"E-GRM-02","E-GRM-03","E-VOC-01"},new[]{"E-WRT-02","E-WRT-03"}),
        new("E-WRT-02","Argumentative Writing","English","writing",new[]{"E-WRT-01"},Array.Empty<string>()),
        new("E-WRT-03","Discursive Writing","English","writing",new[]{"E-WRT-01","E-RDG-04"},Array.Empty<string>()),
        new("E-LIT-01","Literary Devices","English","literature",new[]{"E-RDG-02"},new[]{"E-LIT-02","E-LIT-03"}),
        new("E-LIT-02","Poetry Analysis","English","literature",new[]{"E-LIT-01"},Array.Empty<string>()),
        new("E-LIT-03","Prose & Drama","English","literature",new[]{"E-LIT-01"},Array.Empty<string>()),
        new("E-LST-01","Listening Comprehension","English","listening",Array.Empty<string>(),new[]{"E-LST-02"}),
        new("E-LST-02","Note-Taking & Summary","English","listening",new[]{"E-LST-01"},Array.Empty<string>()),
        new("E-SPK-01","Oral Presentation","English","speaking",new[]{"E-WRT-01"},Array.Empty<string>()),
    };

    public static IReadOnlyDictionary<string, ConceptEntry> ById =
        All.ToDictionary(c => c.Id, c => c);
}
